### ISSUE TITLE
Possible mistake in tool flow diagram

### ISSUE THREAD

**Issue by ctyar** [devlead/Blobify#1]
The tool flow diagram in README.md states if MD5 hash matches, the tool will delete the file and skips on not Matching. I'm guessing this is a typo and it's the other way around.
Also happy to send a PR to fix if that's the case.

**Comment by devlead** [comment]
If the file exists on blob storage and the hashes doesn't match it'll skip that file/won't delete it locally.

If the file already exists on blob storage amd hashes match it won't upload but delete locally.

**Comment by ctyar** [comment]
I see, the delete or skip refers to the source file and not the destination.
Thanks for clarification.
